services:
  db:
    image: laurapihamaa623/discussion-forum:database
    restart: always
    environment: 
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: discussion-forum
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  adminer:
    restart: always
    ports:
      - 8088:8080
  backend:
    image: laurapihamaa623/discussion-forum:backend
    build:
      context: ./DiscussionForum
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5055:5055
    depends_on:
      - db
  frontend:
    image: laurapihamaa623/discussion-forum:frontend
    build:
      context: ./dicussion-forum-front
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
